#!/bin/bash
#SBATCH -p parallel
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 28
#SBATCH --mem 128G
#SBATCH --time 20:00:00 
#SBATCH --mail-user aymanns
#SBATCH --mail-type FAIL
module load gcc/7.4.0 python/3.7.3
source /home/aymanns/ofco/examples/venvs/venv-for-registration/bin/activate
echo STARTING AT `date`
python /home/aymanns/ofco/examples/register.py /scratch/aymanns/200901_G23xU1/Fly1/007_coronal/ /scratch/aymanns/200901_G23xU1/Fly1/ref_frame.tif
#python /home/aymanns/ofco/examples/register.py /scratch/aymanns/200909_G23xU1/Fly1/003_coronal/ /scratch/aymanns/200909_G23xU1/Fly1/ref_frame.tif
echo FINISHED at `date`	
